/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-07-17 07:50:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/sandstone/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("<link href=\"css/home.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js\"></script>\n");
      out.write("\n");
      out.write("<body >\n");
      out.write("<div class=\"main_container\">\n");
      out.write("\n");
      out.write("<div class=\"header_content content_background_gradient\">\n");
      out.write("\t<div class= \"header_content_div\">\n");
      out.write("\t\t<p class=\"header_content_div_text\"> Mobenga SportPerson's Test Application</p>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"main_content\">\n");
      out.write("\t<div class=\"main_div\">\n");
      out.write("\t\t<div ng-app=\"myApp\" ng-controller=\"personCtrl\">\n");
      out.write("\t\t\t<div class=\"brief_list_content\" ng-hide=\"briefContent\">\n");
      out.write("\t\t\t<p class=\"content_brief_header_style\">Sports Persons Brief List</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<table class=\"table table-striped\">\n");
      out.write("\t\t\t\t  <thead><tr>\n");
      out.write("\t\t\t\t    <th></th>\n");
      out.write("\t\t\t\t    <th><a href=\"#\" ng-click=\"sortType = 'firstName'; sortReverse = !sortReverse\">First Name\n");
      out.write("\t\t\t\t    \t        <span ng-show=\"sortType == 'firstName' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'firstName' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("\t\t\t\t    </a></th>\n");
      out.write("\t\t\t\t    <th><a href=\"#\" ng-click=\"sortType = 'lastName'; sortReverse = !sortReverse\">Last Name\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'lastName' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'lastName' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'teamName'; sortReverse = !sortReverse\">Team Name\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'teamName' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'teamName' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'age'; sortReverse = !sortReverse\">Age\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'age' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'age' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'height'; sortReverse = !sortReverse\">Height&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'height' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'height' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'weight'; sortReverse = !sortReverse\">Weight\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'weight' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'weight' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'positionText'; sortReverse = !sortReverse\">Position\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'positionText' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'positionText' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'apps'; sortReverse = !sortReverse\">Apps\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'apps' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'apps' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'goal'; sortReverse = !sortReverse\">Goal\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'goal' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'goal' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'assistTotal'; sortReverse = !sortReverse\">Assist\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'assistTotal' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'assistTotal' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'redCard'; sortReverse = !sortReverse\">Red Card\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'redCard' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'redCard' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\t     <th><a href=\"#\" ng-click=\"sortType = 'yellowCard'; sortReverse = !sortReverse\">Yellow Card\n");
      out.write("\t\t\t\t    \t\t\t<span ng-show=\"sortType == 'yellowCard' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("       \t\t\t\t\t\t\t<span ng-show=\"sortType == 'yellowCard' && sortReverse\" class=\"fa fa-caret-up\"></span></a></th>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t   \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t\t  </tr></thead>\n");
      out.write("\t\t\t\t  <tbody>\n");
      out.write("\t\t\t\t  <tr ng-repeat=\"p in persons | orderBy:sortType:sortReverse\">\n");
      out.write("\t\t\t\t    <td>\n");
      out.write("\t\t\t\t      <button class=\"view_button btn btn-success\" ng-click=\"viewUser(p.playerId)\">\n");
      out.write("\t\t\t\t      \t<span class=\"glyphicon glyphicon-user\"></span> View\n");
      out.write("\t\t\t\t      </button>\n");
      out.write("\t\t\t\t    </td>\n");
      out.write("\t\t\t\t    <td>{{ p.firstName | uppercase }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.lastName  | uppercase}}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.teamName | uppercase}}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.age }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.height + ' cm'}} </td>\n");
      out.write("\t\t\t\t    <td>{{ p.weight + ' kg'}}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.positionText }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.apps }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.goal }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.assistTotal }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.redCard }}</td>\n");
      out.write("\t\t\t\t    <td>{{ p.yellowCard }}</td>\n");
      out.write("\t\t\t\t    \t    \n");
      out.write("\t\t\t\t  </tr></tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"detailed_list_content\" ng-hide=\"detailedContent\">\n");
      out.write("\t\t\t<div class=\"personal_information_content\">\n");
      out.write("\t\t\t<p class=\"content_header_style\">Personal Information</p>\n");
      out.write("\t\t\t<div class=\"back_button\">\n");
      out.write("\t\t\t\t<button class=\"btn \" ng-click=\"backToUserList()\">\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-arrow-left\"></span>\n");
      out.write("\t\t\t\t      \tBack\n");
      out.write("\t\t\t\t      </button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t<table class=\"personal_information_table table table-striped\">\n");
      out.write("\t\t\t\t  <thead><tr>\n");
      out.write("\t\t\t\t\t<th>Player Id</th>\t\t\t\t  \n");
      out.write("\t\t\t\t    <th>First Name</th>\n");
      out.write("\t\t\t\t    <th>Last Name</th>\n");
      out.write("\t\t\t\t    <th>Active</th>\n");
      out.write("\t\t\t\t    <th>Operation</th>\n");
      out.write("\t\t\t\t    <th>Team Id</th>\n");
      out.write("\t\t\t\t    <th>Team Name</th>\n");
      out.write("\t\t\t\t    <th>Played Positions</th>\n");
      out.write("\t\t\t\t    <th>Age</th>\n");
      out.write("\t\t\t\t    <th>Height</th>\n");
      out.write("\t\t\t\t    <th>Weight</th>\n");
      out.write("\t\t\t\t    <th>Position </th>\n");
      out.write("\n");
      out.write("\t\t\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t\t  </tr></thead>\n");
      out.write("\t\t\t\t  <tbody><tr >\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.playerId }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.firstName | uppercase }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.lastName | uppercase }}</td>\n");
      out.write("\t\t\t\t    <td>{{ {true:'YES', false:'NO'}[detailedPerson.isActive]}}</td>\n");
      out.write("\t\t\t\t    <td>{{ {true:'YES', false:'NO'}[ detailedPerson.isOpta] }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.teamId }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.teamName | uppercase }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.playedPositions }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.age }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.height + ' cm' }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.weight + ' kg'}}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.positionText }}</td>\n");
      out.write("\t\t\t\t    \t    \n");
      out.write("\t\t\t\t  </tr></tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<div class=\"league_stats_content\">\n");
      out.write("\t\t\t<p class=\"content_header_style\">Leauge Statistics</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<table class=\"league_stats_table table table-striped\">\n");
      out.write("\t\t\t\t  <thead><tr>\n");
      out.write("\t\t\t\t    <th>Ranking</th>\n");
      out.write("\t\t\t\t    <th>Season No</th>\n");
      out.write("\t\t\t\t    <th>Season Name</th>\n");
      out.write("\t\t\t\t    <th>Tournament Id</th>\n");
      out.write("\t\t\t\t    <th>Tournament Region ID</th>\n");
      out.write("\t\t\t\t    <th>Tournament Region Code</th>\n");
      out.write("\t\t\t\t    <th>Region Code</th>\n");
      out.write("\t\t\t\t    <th>Tournament Name</th>\n");
      out.write("\t\t\t\t    <th>Tournament Short Name</th>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t\t  </tr></thead>\n");
      out.write("\t\t\t\t  <tbody><tr >\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.ranking }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.seasonId }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.seasonName | uppercase}}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.tournamentId }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.tournamentRegionId }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.tournamentRegionCode }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.regionCode | uppercase}}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.tournamentName | uppercase }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.tournamentShortName}}</td>\n");
      out.write("\n");
      out.write("\t\t\t\t    \t    \n");
      out.write("\t\t\t\t  </tr></tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<div class=\"match_statistics_content\">\n");
      out.write("\t\t\t<p class=\"content_header_style\">Match Statistics</p>\n");
      out.write("\t\t\t\t<table class=\"match_statistics_table table table-striped\">\n");
      out.write("\t\t\t\t  <thead><tr>\n");
      out.write("\t\t\t\t    <th>Appearances</th>\n");
      out.write("\t\t\t\t    <th>Substitutions</th>\n");
      out.write("\t\t\t\t    <th>Played Time</th>\n");
      out.write("\t\t\t\t    <th>Goal</th>\n");
      out.write("\t\t\t\t    <th>Assist</th>\n");
      out.write("\t\t\t\t    <th>Yellow Card</th>\n");
      out.write("\t\t\t\t    <th>Red Card</th>\n");
      out.write("\t\t\t\t    <th>Man of the Match Count</th>\n");
      out.write("\t\t\t\t    <th>Name</th>\n");
      out.write("\t\t\t\t    <th>Man of the Match</th>\n");
      out.write("\t\t\t\t    <th>Positions</th>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t\t  </tr></thead>\n");
      out.write("\t\t\t\t  <tbody><tr >\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.apps }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.subOn }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.minsPlayed + ' mins' }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.goal }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.assistTotal }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.yellowCard }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.redCard }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.manOfTheMatch }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.name | uppercase}}</td>\n");
      out.write("\t\t\t\t    <td>{{ {true:'YES', false:'NO'}[ detailedPerson.isManOfTheMatch]}}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.playedPositionsShort }}</td>\n");
      out.write("\t\t\t\t    \t    \n");
      out.write("\t\t\t\t  </tr></tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<div class=\"rating_statistics_content\">\n");
      out.write("\t\t\t\t<p class=\"content_header_style\">Rating Statistics</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<table class=\"rating_statistics_table table table-striped\">\n");
      out.write("\t\t\t\t  <thead><tr>\n");
      out.write("\t\t\t\t    <th>Rating</th>\n");
      out.write("\t\t\t\t    <th>Shots per Game</th>\n");
      out.write("\t\t\t\t    <th>Aerial Won Per Game</th>\n");
      out.write("\t\t\t\t    <th>Succes Pass Rate</th>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t\t  </tr></thead>\n");
      out.write("\t\t\t\t  <tbody><tr >\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.rating | number:2}}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.shotsPerGame | number:2  }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.aerialWonPerGame | number:2 }}</td>\n");
      out.write("\t\t\t\t    <td>{{ detailedPerson.passSuccess | number:2}}</td>\n");
      out.write("\t\t\t\t    \t    \n");
      out.write("\t\t\t\t  </tr></tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\t<div class=\"content_background_gradient footer_content\">\n");
      out.write("\t\t<div class= \"footer_content_div\">\n");
      out.write("\t\t\t<p class=\"footer_content_div_text\"> This content created by Omer Caner EREN, canereren112@gmail.com</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src = \"js/sportPersons.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
